name: UHCCore
main: FRISCOWZ\Main
api: 1.13.0
version: 0.1
author: OpenBuild Dev Team
commands:
 uhc:
  description: A simple UHC Core Plugin for ImagicalMine
  permission: uhc.cmd
  usage: /uhc help
